name: PR Factory

on:
  workflow_dispatch: {}
# Uncomment the following cron schedule to run this workflow every 30 minutes
#   schedule:
#     - cron: 0/30 * * * *

jobs:
  create-pr:
    # needs: merge-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: choose secret
        id: choose-secret
        run: |
          case $(( RANDOM % 3 )) in
          0)
            echo "secret_name=ELI_PAT" >> $GITHUB_OUTPUT
            echo "Impersonating Eli"
            ;;
          1)
            echo "secret_name=ELI_PAT" >> $GITHUB_OUTPUT
            echo "Impersonating Eli"
            ;;
          2)
            echo "secret_name=ELI_PAT" >> $GITHUB_OUTPUT
            echo "Impersonating Eli"
            ;;            
          esac

      - name: trunk install
        uses: trunk-io/trunk-action/install@v1
        with:
          tools: gh

      - uses: robinraju/release-downloader@v1.9
        with:
          repository: trunk-io/mergequeue-tool
          latest: true
          tarBall: true
          preRelease: false
          extract: true

      - name: run mq
        id: edits
        run: ./mq generate
        env:
          GH_TOKEN: ${{ secrets[steps.choose-secret.outputs.secret_name] }}

      - name: run mq
        if: always()
        id: clean
        run: ./mq housekeeping
        env:
          GH_TOKEN: ${{ secrets[steps.choose-secret.outputs.secret_name] }}
